# Generated by Django 4.0.4 on 2022-04-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('days_meals', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodComponents',
            new_name='FoodComponent',
        ),
    ]
