# Generated by Django 4.0.4 on 2022-04-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days_meals', '0003_rename_foodcomponents_foodcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcomponent',
            name='carbon_footprint',
            field=models.FloatField(null=True),
        ),
    ]
