# Generated by Django 4.0.4 on 2022-04-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days_meals', '0004_foodcomponent_carbon_footprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='daymeals',
            name='items',
            field=models.ManyToManyField(related_name='meals', to='days_meals.foodcomponent'),
        ),
    ]
