# Generated by Django 4.0.4 on 2022-04-19 14:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('days_meals', '0005_daymeals_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DayMeals',
            new_name='DayMeal',
        ),
    ]
