# Generated by Django 4.0.4 on 2022-04-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days_meals', '0006_rename_daymeals_daymeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='daymeal',
            name='portion',
            field=models.IntegerField(null=True),
        ),
    ]
