# Generated by Django 4.0.4 on 2022-04-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('days_meals', '0007_daymeal_portion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daymeal',
            name='portion',
        ),
    ]
